openapi: 3.0.0
info:
  title: pypyr scheduler
  version: '1.0'
  contact:
    url: 'https://github.com/dzerrenner'
    email: dazer017@gmail.com
    name: David Zerrenner
  license:
    name: MIT
    url: 'https://choosealicense.com/licenses/mit/'
  description: Pypyr-Scheduler API spec
servers:
  - url: 'http://localhost:8080'
paths:
  /status:
    get:
      operationId: pyrsched.api.status.get
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_running:
                    type: boolean
                required:
                  - is_running
      description: Returns some status information for the scheduler
      tags:
        - Operations
  /pipelines:
    get:
      summary: Your GET endpoint
      tags:
        - Pipelines
      responses:
        '200':
          description: OK
      operationId: pyrsched.api.pipelines.all
      description: Get pipeline descriptions
  '/pipelines/{pipeline-id}':
    get:
      summary: Your GET endpoint
      tags:
        - Pipelines
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pipeline'
      operationId: pyrsched.api.pipelines.get
      description: Get a single pipeline description
    parameters:
      - schema:
          type: string
        name: pipeline-id
        in: path
        required: true
components:
  schemas:
    Job:
      title: Job
      type: object
      properties:
        version:
          type: integer
        id:
          type: string
        func:
          type: string
        trigger:
          type: object
          properties:
            version:
              type: integer
            timezone:
              type: string
            start_date:
              type: string
            end_date:
              type: string
            interval:
              type: string
            jitter:
              type: string
        executor:
          type: string
        args:
          type: array
          items:
            type: string
        kwargs:
          type: object
        name:
          type: string
        misfire_grace_time:
          type: integer
        coalesce:
          type: string
        max_instances:
          type: integer
        next_run_time:
          type: string
      required:
        - version
        - id
        - func
        - trigger
        - executor
        - args
        - kwargs
        - name
    Pipeline:
      title: Pipeline
      type: object
      properties:
        id:
          $ref: ''
